apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-dep
spec:
  selector:
    matchLabels:
      app: green
  replicas: 1
  template:
    metadata:
      labels:
        app: green
        canary: green-blue
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
