apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: yanivomc/spring-music:latest
        volumeMounts:
          - mountPath: "/var/www/html"
            name: pod-volume-html
      volumes:
      - name: pod-volume-html
