apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-spring
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
